### ISSUE TITLE
IsFiles decorator issue

### ISSUE THREAD

**Issue by Visterious** [eddienubes/validness#37]
When your dto have IsFiles decorator and some Transform decorator at the same time, then Transform decorator's callback will call as much times as files was attached to the request. 

I guess this is a bug and unexpected behavior
![image_2023-04-05_133212995](https://user-images.githubusercontent.com/57287313/230055805-417c4314-332b-4e52-9722-cc7e7665a895.png)

**Comment by eddienubes** [comment]
closed as refined in PR #41
